services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"  # 控制台端口
    volumes:
      - ./data:/data
      - ./scripts/start.sh:/start.sh
      - ./scripts/init.sh:/init.sh
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_PROMETHEUS_AUTH_TYPE: public
    entrypoint: ["/bin/sh", "-c", "/start.sh"]
    networks:
      - app-net

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - minio
    networks:
      - app-net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=minioadmin
      - GF_SECURITY_ADMIN_PASSWORD=minioadmin
    depends_on:
      - prometheus
    networks:
      - app-net

volumes:
  minio-data:

networks:
  app-net:
    driver: bridge
